dname='E:\DelftFM\AndrewRuns\RoughnessTesting\Manning\r_316\';
mname    = 'ps_2d_map.nc';
grd         = dflowfm.readNetOld([dname,mname]);

face.mask = true(1,grd.face.FlowElemSize);
[xg,yg] = dflowfm.peri2cell(grd.face.FlowElemCont_x(:,face.mask),...
    grd.face.FlowElemCont_y(:,face.mask));
tri.mask = face.mask(grd.map3);



ldb=landboundary('read',['C:\Users\ahooshmand\Desktop\PS_COSMOS\Thesis_Modeling\FM\LandBoundaryFiles\',...
    'WA_coastline.ldb']);
addpath C:\Functions_Matlab\resl2rgb
bname='E:\Abbas\Modeling Resources\PS_DEM\GEBCO\';
bfile='GEBCO_2014_2D_-130.0_46.8_-122.0_51.8.nc';
lat=ncread([bname,bfile],'lat');
lon=ncread([bname,bfile],'lon');
z=ncread([bname,bfile],'elevation');
xd=vdist(lat(1),lon(1),lat(1),lon(end));
yd=vdist(lat(1),lon(1),lat(end),lon(end));
xi=linspace(0,xd,numel(lon));
yi=linspace(0,yd,numel(lat));
hs=real2rgb(hillshade(z',xi,yi,'zfactor',2),'gray',[0 255]);

fun=@(x)([min(x) max(x)]);
lonlim=[-129.22892620896	-122];
latlim=[46.9675525931304	51.6220608123692];


[lonm,latm]=meshgrid(lon,lat);

latlim2=[47 48.9];
lonlim2=[-124.75 -122.05];

f=figure;
set(f,'renderer','zbuffer','units','inches',...
    'position',[0 0 9 7],...
    'paperpositionmode','au')

axesm('mercator')
hold on 
[x,y]=mfwdtran(latm,lonm);
[xp,yp]=mfwdtran(grd.node.y,grd.node.x);
[xl,yl]=mfwdtran(latlim,lonlim);

sh=surf(x,y,zeros(size(x)),hs);
set(sh,'edgecolor','none')



hold on

z=0;
p = trisurf(grd.tri(tri.mask,:),xp,yp,zeros(size(xp)),...
    grd.face.FlowElem_z(grd.map3(tri.mask)));
set(p,'FaceColor','flat','edgecolor','none'); 
plotm(ldb(:,2),ldb(:,1),'k-')

linem(latlim2,[lonlim2(1) lonlim2(1)],'-','color','k')
linem(latlim2,[lonlim2(2) lonlim2(2)],'-','color','k')
linem([latlim2(1) latlim2(1)],lonlim2,'-','color','k')
linem([latlim2(2) latlim2(2)],lonlim2,'-','color','k')

xp1=lonlim2(1)+0.05*diff(lonlim2);
yp1=latlim2(1)+0.95*diff(latlim2);
textm(yp1,xp1,'\bf\itDetail area',...
    'backgroundcolor','w','margin',1)

setm(gca,'maplonlimit',lonlim,...
    'maplatlimit',latlim,...
    'mlabelloc',2,...
    'mlineloc',2,...
    'plabelloc',2,...
    'plineloc',2,...
    'mlabelparallel','north',...
    'plabelmeridian','west',...
    'parallellab','on',...
    'meridianlab','on',...
    'mlabelround',0,...
    'plabelround',0,...
    'grid','on',...
    'flinewidth',1,...
    'frame','on',...
    'labelformat','none');
colormap(jet)
set(gca,'visible','off',...
    'clim',[-3000 0],...
    'xlim',xl,...
    'ylim',yl)
lx=lonlim(1)+0.02*diff(lonlim);
ly=latlim(1)+0.05*diff(latlim);

[xr,yr]=projfwd(getm(gca),ly,lx);
rh = scaleruler;
setm(rh,'units','km',...
    'majortick',(0:50:150),...
    'majorticklength',5,...
    'minortick',[0 0],...
    'minorticklength',0,...
    'xloc',xr,...
    'yloc',yr,...
    'color','k',...
    'linewi',2,...
    'fontang','it',...
    'fontweight','b')


c2=colorbar('horiz');
cp=get(c2,'position');
cp2=cp;
cp2(1)=cp(1)+0.425;
cp2(2)=cp(2)+0.7;
cp2(3)=cp(3)*0.3;
cp2(4)=cp(4)*0.8;
set(c2,'position',cp2);
set(get(c2,'xlabel'),'string',...
    '\bf\itElevation (m)')

%%
%%%%%-----------------------------------------------------

serverURL = ['http://ows.terrestris.de/osm/service?SERVICE',...
    '=WMS&VERSION=1.1.1&REQUEST=GetCapabilities'];
info = wmsinfo(serverURL);



imageLength=1024*2;

orthoLayer = info.Layer(2);
 [A, R] = wmsread(orthoLayer, 'Latlim', latlim2,...
            'Lonlim', lonlim2, ...
            'ImageHeight', imageLength,...
            'ImageWidth', imageLength');

f=figure;
set(f,'renderer','zbuffer','units','inches',...
    'position',[0 0 9 7],...
    'paperpositionmode','au')

axesm('mercator')
hold on 
geoshow(A,R)
[xl,yl]=mfwdtran(latlim2,lonlim2);

z=0;
p = trisurf(grd.tri(tri.mask,:),xp,yp,zeros(size(xp)),...
    grd.face.FlowElem_z(grd.map3(tri.mask)));
set(p,'FaceColor','flat','edgecolor','none'); 
plotm(ldb(:,2),ldb(:,1),'k-')

setm(gca,'maplonlimit',lonlim2,...
    'maplatlimit',latlim2,...
    'mlabelloc',1,...
    'mlineloc',1,...
    'plabelloc',1,...
    'plineloc',1,...
    'mlabelparallel','north',...
    'plabelmeridian','west',...
    'parallellab','on',...
    'meridianlab','on',...
    'mlabelround',0,...
    'plabelround',0,...
    'grid','on',...
    'flinewidth',1,...
    'frame','on',...
    'labelformat','none');

set(gca,'visible','off',...
    'xlim',xl,...
    'ylim',yl)
lx=lonlim2(1)+0.02*diff(lonlim2);
ly=latlim2(1)+0.01*diff(latlim2);

[xr,yr]=projfwd(getm(gca),ly,lx);
rh = scaleruler;
setm(rh,'units','km',...
    'majortick',(0:25:50),...
    'majorticklength',5,...
    'minortick',[0 0],...
    'minorticklength',0,...
    'xloc',xr,...
    'yloc',yr,...
    'color','k',...
    'linewi',2,...
    'fontang','it',...
    'fontweight','b')
colormap(jet)
caxis([-300 10])

c2=colorbar('horiz');
set(c2,'xtick',[-300:100:-100,10])
cp=get(c2,'position');
cp2=cp;
cp2(1)=cp(1)-0.035;
cp2(2)=cp(2)-0.08;
cp2(3)=cp(3)*0.4;
cp2(4)=cp(4)*0.8;
set(c2,'position',cp2);
set(get(c2,'xlabel'),'string',...
    '\bf\itElevation (m)')
