%% Load Data
clearvars
% Add OET !!!!!!!!!!!!!
% Output Folder and File Location and Name
% ------- Will require Changing --------------------
nc_fol = 'E:\DelftFM\AndrewRuns\RoughnessTesting\Manning\r_316\';
nc_file = 'ps_2d_map.nc';
info = ncinfo([nc_fol nc_file]);
basemap = 'C:\Users\ahooshmand\Desktop\FM_Plotting\tiffs\bbay_1.mat';

% Get time info from MDU file
ref_date = datenum(2017,01,01); % Simulation Reference Date
sim_start = ref_date+(19440/(60*24)); % Start of simulation w.r.t ref_date
sim_end = ref_date+(129600/(60*24)); % End of simulation w.r.t ref_date
map_delay = 1166400/(60*60*24); % Dealy in writing map output from .mdu
map_start = sim_start+map_delay; % datenum start of map output
map_time = map_start:1/24:map_start+length(time)-1; % datenum of map output time


% Load in Grid 
G = dflowfm.readNet([nc_fol nc_file]); % Load in Grid Structure
xg = G.node.x(G.edge.NetLink);
yg = G.node.y(G.edge.NetLink);
xg(3,:)=NaN;
yg(3,:)=NaN;



D = dflowfm.readMap([nc_fol nc_file]); % Load in Data
bl = ncread([nc_fol nc_file],'FlowElem_bl',[1],[Inf]);
D.face.bl = bl;
% info = ncinfo([nc_fol nc_file]);
% T.datenum = nc_cf_time([nc_fol nc_file]); % Should load in time 

% load Individual Timeseries Data - 25 seconds to load
tic
vx = ncread([nc_fol nc_file],'ucx')'; % Velocities
vy = ncread([nc_fol nc_file],'ucy')';
time = ncread([nc_fol nc_file],'time');
wl = ncread([nc_fol nc_file],'waterdepth');
bl = ncread([nc_fol nc_file],'FlowElem_bl',[1],[Inf]);
toc
% Load Basemap
IM = load('C:\Users\ahooshmand\Desktop\FM_Plotting\tiffs\bbay_1UTM.mat');
% Note 4 base maps exist for bbay, bbay1,bbay2,bbay3,bbay4.  Higher the
% number means higher the resolution on the delta 
%% Plotting  in general
figure(1);clf 

% Default Plotting
dflowfm.plotMap(G,D) % Default plots WL 


%% Plot Bed Level
clf
imagesc(IM.xm,IM.ym,IM.im)
set(gca,'ydir','normal')
hold on 
dflowfm.plotMap(G,D,'parameter','bl') % Plot Bed Level
clrmap('C:\OET\matlab\applications\delft3d_matlab\colormaps\gist_earth.clrmap'); % Colormap that Deltares uses - feel free to change
caxis([-20 5]) % Bathy Limits

% xlim([-122.75 -122.4])
% ylim([48.55 48.85])
xlim([5.2*10^5 5.45*10^5])
ylim([5.377*10^6 5.412*10^6])
%% Plot WL with Velocity Vectors 
clf
imagesc(IM.xm,IM.ym,IM.im)
set(gca,'ydir','normal')
hold on 
dflowfm.plotMap(G,D,'parameter','dep')
colormap(parula)
caxis([-20 4])
hold on 
% quiver(G.face.FlowElem_x',G.face.FlowElem_y',D.face.u,D.face.v,'w')
for i = 1:10
    quiver(G.face.FlowElem_x',G.face.FlowElem_y',vx(i,:)',vy(i,:)','w')
    pause(0.25)
%     xlim([-122.75 -122.4])
%     ylim([48.55 48.85])
xlim([5.2*10^5 5.45*10^5])
ylim([5.377*10^6 5.412*10^6])
end
% xlim([-122.75 -122.4])
% ylim([48.55 48.85])
xlim([5.2*10^5 5.45*10^5])
ylim([5.377*10^6 5.412*10^6])
%% Plot WL through time 
% NOTE FOR SOME REASON WITH PLOTTING YOU CANNOT STOP THE LOOP WITH THIS OET
% PLOTTING SO TEST WITH SHORT TIME PERIODS!
clf
imagesc(IM.xm,IM.ym,IM.im)
set(gca,'ydir','normal')
hold on 
for i = 500:600
    dflowfm.plotMap(G,wl(:,i))
    colormap(parula)
    pause(0.25)
    caxis([-4 4])
%     xlim([-122.75 -122.4])
%     ylim([48.55 48.85])
xlim([5.2*10^5 5.45*10^5])
ylim([5.377*10^6 5.412*10^6])
end
% xlim([-122.75 -122.4]) % limits for bbay1
% ylim([48.55 48.85])
xlim([5.2*10^5 5.45*10^5])
ylim([5.377*10^6 5.412*10^6])




%% Plotting of DFM Domain 

clearvars
% Load in Grid
dname='E:\DelftFM\AndrewRuns\RoughnessTesting\Manning\';
fname    = 'salish_sea_net.nc';
grd         = dflowfm.readNet([dname,fname]);

xg = grd.node.x(grd.edge.NetLink);
yg = grd.node.y(grd.edge.NetLink);
xg(3,:)=NaN;
yg(3,:)=NaN;

% dnameh=[dname,'r_316\'];
% fnameh='ps_2d_his.nc';
% stns=cellstr(ncread([dnameh,fnameh],'station_name')');
% dstns={'NOAA_9443090_Neah_Bay';...
%     'NOAA_9444090_Port_Angeles';...
%     'NOAA_9444900_Port_Townsend';...
%     'NOAA_9447130_Seattle';...
%     'NOAA_9446484_Tacoma';...
%     'NOAA_9449424_Cherry_Point'};
% [~,~,istns]=intersect(dstns,stns,'stable');
% gstns=stns(istns);
% lons=cellfun(@(x)(ncread([dnameh,fnameh],'station_x_coordinate',...
%     [x 1],[1 1])'),num2cell(istns));
% lats=cellfun(@(x)(ncread([dnameh,fnameh],'station_y_coordinate',...
%     [x 1],[1 1])'),num2cell(istns));

% Load in LBD and GEBCO DEM
ldb=landboundary('read',['C:\Users\ahooshmand\Desktop\PS_COSMOS\Thesis_Modeling\FM\LandBoundaryFiles\',...
    'WA_coastline.ldb']);
addpath C:\Functions_Matlab\resl2rgb
bname='E:\Abbas\Modeling Resources\PS_DEM\GEBCO\';
bfile='GEBCO_2014_2D_-130.0_46.8_-122.0_51.8.nc';
lat=ncread([bname,bfile],'lat');
lon=ncread([bname,bfile],'lon');
z=ncread([bname,bfile],'elevation');
xd=vdist(lat(1),lon(1),lat(1),lon(end));
yd=vdist(lat(1),lon(1),lat(end),lon(end));
xi=linspace(0,xd,numel(lon));
yi=linspace(0,yd,numel(lat));
hs=real2rgb(hillshade(z',xi,yi,'zfactor',2),'gray',[0 255]);

% rlocs=[-122.869086  47.737296;...
%     -122.587885  47.187664;...
%     -122.909572  47.058475;...
%     -122.652783  47.727286;...
%     -122.924730  47.639832;...
%     -123.126193  48.161717;...
%     -122.363769  47.589485;...
%     -123.574258  48.151710;...
%     -123.077917  47.211642;...
%     -124.363044  48.290389;...
%     -122.687614  47.356550;...
%     -124.677124  48.307490;...
%     -122.297421  48.058815;...
%     -122.700719  47.114956;...
%     -122.582937  48.746604;...
%     -122.445704  47.276299;...
%     -122.493481  48.594663;...
%     -122.484067  48.303545;...
%     -123.130697  47.366370;...
%     -122.294967  48.015249;...
%     -122.426621  48.163621;...
%     -122.297221  48.059632];
% blocs=[-123.165 48.334;...
%     -124.726  48.493];
    
fun=@(x)([min(x) max(x)]);
lonlim=[-129.22892620896	-122];
latlim=[46.9675525931304	51.6220608123692];

[lonm,latm]=meshgrid(lon,lat);

latlim2=[47 48.9];
lonlim2=[-125 -122.05];

addpath('C:\Program Files\MATLAB\R2017b\toolbox\map\mapproj\')
f=figure;
set(f,'renderer','zbuffer','units','inches',...
    'position',[0 0 9 7],...
    'paperpositionmode','au')

axesm('mercator')
hold on 
[x,y]=mfwdtran(latm,lonm);
[xp,yp]=mfwdtran(grd.node.y,grd.node.x);
[xl,yl]=mfwdtran(latlim,lonlim);

sh=surf(x,y,zeros(size(x)),hs);
set(sh,'edgecolor','none')



hold on

lh=plotm(yg(:),xg(:),'-')
plotm(ldb(:,2),ldb(:,1),'k-')

[leg,legh]=legend(sh,'Model domain');
set(leg,'location','northeast','fontang','it',...
    'fontweight','b','autoupdate','off');
set(legh(2),'edgecolor','none',...
    'facecolor',get(lh,'color'))


linem(latlim2,[lonlim2(1) lonlim2(1)],'-','color','k')
linem(latlim2,[lonlim2(2) lonlim2(2)],'-','color','k')
linem([latlim2(1) latlim2(1)],lonlim2,'-','color','k')
linem([latlim2(2) latlim2(2)],lonlim2,'-','color','k')

xp=lonlim2(1)+0.05*diff(lonlim2);
yp=latlim2(1)+0.95*diff(latlim2);
textm(yp,xp,'\bf\itDetail area',...
    'backgroundcolor','w','margin',1)

setm(gca,'maplonlimit',lonlim,...
    'maplatlimit',latlim,...
    'mlabelloc',2,...
    'mlineloc',2,...
    'plabelloc',2,...
    'plineloc',2,...
    'mlabelparallel','north',...
    'plabelmeridian','west',...
    'parallellab','on',...
    'meridianlab','on',...
    'mlabelround',0,...
    'plabelround',0,...
    'grid','on',...
    'flinewidth',1,...
    'frame','on',...
    'labelformat','none');
colormap(jet)
set(gca,'visible','off',...
    'xlim',xl,...
    'ylim',yl)
lx=lonlim(1)+0.02*diff(lonlim);
ly=latlim(1)+0.05*diff(latlim);

[xr,yr]=projfwd(getm(gca),ly,lx);
rh = scaleruler;
setm(rh,'units','km',...
    'majortick',(0:50:150),...
    'majorticklength',5,...
    'minortick',[0 0],...
    'minorticklength',0,...
    'xloc',xr,...
    'yloc',yr,...
    'color','k',...
    'linewi',2,...
    'fontang','it',...
    'fontweight','b')
%%%%%-----------------------------------------------------

serverURL = ['http://ows.terrestris.de/osm/service?SERVICE',...
    '=WMS&VERSION=1.1.1&REQUEST=GetCapabilities'];
info = wmsinfo(serverURL);



imageLength=1024*2;

orthoLayer = info.Layer(2);
 [A, R] = wmsread(orthoLayer, 'Latlim', latlim2,...
            'Lonlim', lonlim2, ...
            'ImageHeight', imageLength,...
            'ImageWidth', imageLength');

f=figure;
set(f,'renderer','zbuffer','units','inches',...
    'position',[0 0 9 7],...
    'paperpositionmode','au')

axesm('mercator')
hold on 
geoshow(A,R)
[xl,yl]=mfwdtran(latlim2,lonlim2);

sh=patchm([0.1 0.1 0 0 0.1],[0 0.1 0.1 0 0],'k');

hold on

gh=plotm(yg(:),xg(:),'-');
plotm(ldb(:,2),ldb(:,1),'k-')

mh=plotm(mdata.lat,mdata.lon,'k>','markerfacecolor',...
    [0.9290    0.6940    0.1250],'markersize',6);

wh=plotm(lats,lons,'rd','markerfacecolor','r');
th=textm(lats,lons,{'NB';'PA';'PT';'SEA';'TAC';'CP'});
set(th,'color','r','verticalalign','top')

dh=plotm(rlocs(:,2),rlocs(:,1),'ks','markerfacecolor','y');
bh=plotm(blocs(:,2),blocs(:,1),'kp','markerfacecolor',...
    [0.8500    0.3250    0.0980],'markersize',10);


[leg,legh]=legend([sh;wh;dh;bh;mh],'Model domain','NOAA water levels',...
    'USGS fluvial inputs','NOAA wave buoys','NCDC met. stations');
set(leg,'location','northwest','fontang','it',...
    'fontweight','b','autoupdate','off');
set(legh(6),'edgecolor','none',...
    'facecolor',get(gh,'color'))

setm(gca,'maplonlimit',lonlim2,...
    'maplatlimit',latlim2,...
    'mlabelloc',1,...
    'mlineloc',1,...
    'plabelloc',1,...
    'plineloc',1,...
    'mlabelparallel','north',...
    'plabelmeridian','west',...
    'parallellab','on',...
    'meridianlab','on',...
    'mlabelround',0,...
    'plabelround',0,...
    'grid','on',...
    'flinewidth',1,...
    'frame','on',...
    'labelformat','none');

set(gca,'visible','off',...
    'xlim',xl,...
    'ylim',yl)
lx=lonlim2(1)+0.02*diff(lonlim2);
ly=latlim2(1)+0.01*diff(latlim2);

[xr,yr]=projfwd(getm(gca),ly,lx);
rh = scaleruler;
setm(rh,'units','km',...
    'majortick',(0:25:50),...
    'majorticklength',5,...
    'minortick',[0 0],...
    'minorticklength',0,...
    'xloc',xr,...
    'yloc',yr,...
    'color','k',...
    'linewi',2,...
    'fontang','it',...
    'fontweight','b')

%%%--------------------------------------------------------------
latlim3=[48.0055182383695 48.2577688255961 ];
lonlim3=[-122.927009914402 -122.528351294616];


serverURL = ['https://basemap.nationalmap.gov/arcgis/services/',...
    'USGSImageryOnly/MapServer/WMSServer?request=GetCapabilities&service=WMS'];
info = wmsinfo(serverURL);



imageLength=1024*2;

orthoLayer = info.Layer(1);
 [A, R] = wmsread(orthoLayer, 'Latlim', latlim3,...
            'Lonlim', lonlim3, ...
            'ImageHeight', imageLength,...
            'ImageWidth', imageLength');

f=figure;
set(f,'renderer','zbuffer','units','inches',...
    'position',[0 0 5 4],...
    'paperpositionmode','au')

axesm('mercator')
hold on 
geoshow(A,R)
[xl,yl]=mfwdtran(latlim3,lonlim3);

sh=patchm([0.1 0.1 0 0 0.1],[0 0.1 0.1 0 0],'k');

hold on

cols=get(gca,'colororder');
gh=plotm(yg(:),xg(:),'-','color',cols(6,:));
plotm(ldb(:,2),ldb(:,1),'k-')

setm(gca,'maplonlimit',lonlim3,...
    'maplatlimit',latlim3,...
    'mlabelloc',0.1,...
    'mlineloc',0.1,...
    'plabelloc',0.1,...
    'plineloc',0.1,...
    'mlabelparallel','north',...
    'plabelmeridian','west',...
    'parallellab','on',...
    'meridianlab','on',...
    'mlabelround',-1,...
    'plabelround',-1,...
    'grid','on',...
    'flinewidth',1,...
    'frame','on',...
    'labelformat','none');

set(gca,'visible','off',...
    'xlim',xl,...
    'ylim',yl)
lx=lonlim3(1)+0.02*diff(lonlim3);
ly=latlim3(1)+0.01*diff(latlim3);

[xr,yr]=projfwd(getm(gca),ly,lx);
rh = scaleruler;
setm(rh,'units','km',...
    'majortick',(0:5:10),...
    'majorticklength',0.5,...
    'minortick',[0 0],...
    'minorticklength',0,...
    'xloc',xr,...
    'yloc',yr,...
    'color','w',...
    'linewi',2,...
    'fontang','it',...
    'fontweight','b')
